export const CART_ACTION_TYPES = {
  SET_CART_ITEMS : 'cart/SET_CART_ITEMS',
  SET_IS_CART_OPEN : 'cart/SET_IS_CART_OPEN',
  SET_BILLING_INFO : 'cart/SET_BILLING_INFO', 
  SET_SHIPPING_INFO : 'cart/SET_SHIPPING_INFO', 
  SET_SHIPPING_SAB: 'cart/SET_SHIPPING_SAB',
}